[package]
name = "shared"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "lib", "staticlib"]

[dependencies]
crux_core = { workspace = true, features = ["typegen"] }
serde = { workspace = true, features = ["derive"] }

[target.'cfg(target_os = "android")'.dependencies]
jni = { version = "0.21", default-features = false }

[dev-dependencies]
crux_core = { workspace = true, features = ["testing"] }
serde_json = "1"
